#!/usr/bin/env node
// Generates the capability parity matrix required by migration plan sections 3.1 and 7.3.
// Merges the extracted source capability map with the manually maintained destination
// status record. Fails loudly if either side is missing a capability so the matrix cannot
// silently drop a row.
//
// Usage: node scripts/migration/parity.mjs

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';

const sourceMapPath = 'docs/migration/inventory/capability-map.json';
const statusPath = 'docs/migration/destination-status.json';
const outDir = 'docs/migration';
for (const file of [sourceMapPath, statusPath]) {
  if (!existsSync(file)) { console.error('Missing input: ' + file + '. Run scripts/migration/capability-map.mjs first.'); process.exit(1); }
}
const sourceMap = JSON.parse(await readFile(sourceMapPath, 'utf8'));
const status = JSON.parse(await readFile(statusPath, 'utf8'));

const rows = sourceMap.rows;
const problems = [];
for (const row of rows) {
  if (!status.statuses[row.id]) problems.push('destination status missing for ' + row.id);
}
for (const id of Object.keys(status.statuses)) {
  if (!rows.some((row) => row.id === id)) problems.push('source map missing for ' + id + ' (status record has no source row)');
}
if (problems.length) { console.error('Parity inputs disagree:\n' + problems.join('\n')); process.exit(1); }

const rank = { DONE: 0, PARTIAL: 1, NOT_STARTED: 2, NOT_APPLICABLE: 3 };
const counts = {};
const merged = rows.map((row) => {
  const destination = status.statuses[row.id];
  counts[destination.status] = (counts[destination.status] || 0) + 1;
  const sourceFiles = [...new Set([...Object.values(row.resolvedSymbols).flat(), ...row.familyFiles])].sort();
  return {
    id: row.id,
    capability: row.name,
    destinationOwner: row.destinationOwner,
    taskAnchor: row.taskAnchor,
    migEpic: destination.migEpic,
    symbols: Object.keys(row.resolvedSymbols),
    sourceFiles,
    sourceFileCount: sourceFiles.length,
    domainApi: destination.status,
    dataReadiness: 'NOT_ASSESSED',
    uiJourney: destination.status === 'PARTIAL' ? 'PARTIAL' : 'NOT_IMPLEMENTED',
    providerAcceptance: 'NOT_VERIFIED',
    targetFiles: destination.targetFiles,
    evidence: destination.evidence,
  };
}).sort((a, b) => (rank[a.domainApi] ?? 9) - (rank[b.domainApi] ?? 9) || a.id.localeCompare(b.id));

const cell = (value) => value.replaceAll('|', '\\|');
const list = (files, limit = 4) => files.length === 0 ? '—' : files.slice(0, limit).map((f) => '`' + f + '`').join('<br>') + (files.length > limit ? '<br>… ' + (files.length - limit) + ' more' : '');

const lines = [
  '# Capability parity matrix (C01–C38)',
  '',
  'Generated by `scripts/migration/parity.mjs` from `docs/migration/inventory/capability-map.json` and',
  '`docs/migration/destination-status.json`. Source references are textual extractions from the pinned',
  'AuditSphere commit; destination status is a maintained record, not an inference.',
  '',
  'Status legend: **DONE** (criterion met with evidence), **PARTIAL** (real code exists but the',
  'preservation criterion is unmet), **NOT_STARTED**, **NOT_APPLICABLE** (named approved reason required).',
  '',
  '## Disposition counts',
  '',
  '| Status | Capabilities |',
  '| --- | ---: |',
  ...Object.entries(counts).sort().map(([k, v]) => '| ' + k + ' | ' + v + ' |'),
  '',
  '## Destination status by capability',
  '',
  '| ID | Legacy capability | Source (sample paths) | Files | Destination owner | Domain/API | UI journey | Provider | MIG epic |',
  '| --- | --- | --- | ---: | --- | --- | --- | --- | --- |',
  ...merged.map((row) => '| ' + [row.id, cell(row.capability), list(row.sourceFiles), row.sourceFileCount, cell(row.destinationOwner), row.domainApi, row.uiJourney, row.providerAcceptance, row.migEpic].join(' | ') + ' |'),
  '',
  '## Evidence and remaining gaps',
  '',
  ...merged.flatMap((row) => [
    '### ' + row.id + ' — ' + row.capability,
    '',
    '- Destination status: **' + row.domainApi + '** (UI journey: ' + row.uiJourney + '; data migration readiness: ' + row.dataReadiness + '; provider acceptance: ' + row.providerAcceptance + ')',
    '- Destination owner: ' + row.destinationOwner,
    '- Existing task anchor: ' + row.taskAnchor + '; migration epic: ' + row.migEpic,
    '- Source symbols resolved: ' + (row.symbols.length ? row.symbols.map((s) => '`' + s + '`').join(', ') : '— (family/keyword extraction only)'),
    '- Source files: ' + (row.sourceFiles.length ? row.sourceFiles.map((f) => '`' + f + '`').join(', ') : '—'),
    '- Destination files: ' + (row.targetFiles.length ? row.targetFiles.map((f) => '`' + f + '`').join(', ') : '—'),
    '- Evidence / gap: ' + row.evidence,
    '',
  ]),
  '## Required four-state discipline',
  '',
  'Migration plan section 7.3 requires four independent states per capability: domain/API parity,',
  'data migration readiness, UI journey parity and operational/provider acceptance. This matrix',
  'carries all four. `dataReadiness` stays **NOT_ASSESSED** until a cohort and its source snapshot are',
  'declared, because no legacy data has been inventoried into the destination. `providerAcceptance`',
  'stays **NOT_VERIFIED** until live Microsoft tenant evidence exists; local adapters and fixtures are',
  'not provider acceptance.',
  '',
].join('\n');

await mkdir(outDir, { recursive: true });
await writeFile(path.join(outDir, '02-capability-parity-matrix.md'), lines);
await writeFile(path.join(outDir, 'inventory', 'parity.json'), JSON.stringify({ generatedAt: new Date().toISOString(), sourceCommit: sourceMap.sourceCommit ?? null, counts, rows: merged }, null, 2) + '\n');
console.log('parity rows=' + merged.length + ' ' + JSON.stringify(counts));
