export type ModuleName = 'Commercial' | 'Governance' | 'Fieldwork' | 'Reporting' | 'Practice';
export interface ScreenField { key: string; label: string; type?: 'text' | 'textarea' | 'date' | 'email' | 'decimal' | 'integer' | 'select'; required?: boolean; options?: readonly string[]; }
export interface ModuleScreen { id: string; module: ModuleName; title: string; description: string; fields: readonly ScreenField[]; columns: readonly { key: string; label: string }[]; endpoint?: string; collection?: string; action?: string; guidance: readonly string[]; }
const text = (key: string, label: string, required = true): ScreenField => ({ key, label, required });
const memo = (key: string, label: string, required = true): ScreenField => ({ key, label, type: 'textarea', required });
const date = (key: string, label: string): ScreenField => ({ key, label, type: 'date', required: true });
const money = (key: string, label: string): ScreenField => ({ key, label, type: 'decimal', required: true });
const choice = (key: string, label: string, options: readonly string[]): ScreenField => ({ key, label, type: 'select', required: true, options });
function screen(module: ModuleName, id: string, title: string, description: string, fields: ScreenField[], guidance: string[], endpoint?: string, action?: string, columnKeys?: string[], collection?: string): ModuleScreen {
  return { module, id, title, description, fields, guidance, endpoint, action, collection, columns: (columnKeys ?? fields.slice(0, 3).map(f => f.key)).map(key => ({ key, label: fields.find(f => f.key === key)?.label ?? key.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase()) })) };
}
export const moduleScreens: readonly ModuleScreen[] = [
  screen('Commercial','leads','Lead pipeline','Capture enquiries and prepare the next commercial conversation.',[text('legalName','Legal entity name'),choice('channel','Enquiry channel',['Phone','WhatsApp','Email','Website']),text('contactName','Primary contact'),{...text('email','Contact email'),type:'email'},memo('scope','Requested engagement scope')],['Capture the minimum entity and contact profile.','Client onboarding requires commercial acceptance and separate Partner risk clearance.']),
  screen('Commercial','entities','Entities & contacts','Organize corporate relationships and notification contacts.',[text('legalName','Legal entity name'),text('registration','Registration number'),text('parent','Holding company',false),choice('relationship','Entity relationship',['Independent','Holding','Subsidiary','Affiliate']),text('liaison','Audit liaison'),text('financeContact','Finance contact'),text('executiveContact','Executive contact')],['Financial notifications go to the designated finance contact.','Audit requests go to the audit liaison; representation requests go to management.']),
  screen('Commercial','proposals','Quotes & proposals','Prepare engagement scope, fees and deliverables for client review.',[text('entity','Client legal name'),choice('format','Proposal format',['Brief quotation','Comprehensive proposal']),date('periodEnd','Statutory period end'),money('fee','Professional fee · QAR'),memo('scope','Engagement scope'),date('deadline','Submission deadline')],['Standard payment terms are 50% advance and 50% at the draft-report milestone.','Fee calculation, version approval and dispatch remain server-controlled.']),
  screen('Commercial','onboarding','Dual-key onboarding','Review client approval and independent risk clearance.',[text('entity','Client legal name'),text('proposalReference','Accepted proposal reference'),memo('clientApproval','Client acceptance evidence'),memo('partnerClearance','Partner AML/KYC clearance evidence')],['Both keys are required before generating an engagement letter.','A prepared checklist is not a recorded Partner approval.']),
  screen('Commercial','letters','Engagement letters','Prepare the ISA 210 engagement terms.',[text('legalName','Client legal name'),choice('type','Engagement type',['Statutory audit','Review engagement','Agreed-upon procedures']),date('periodStart','Period start'),date('periodEnd','Period end'),money('fee','Agreed fee · QAR'),memo('terms','Engagement terms')],['Use the approved template for the engagement type.','Signature artwork and authorization must bind the exact generated version.']),
  screen('Commercial','advance','Advance billing & receipts','Prepare payment references and portal activation evidence.',[text('invoice','Advance invoice reference'),money('amount','Payment amount · QAR'),choice('method','Payment method',['Bank transfer','Cheque','Cash']),text('transaction','Transaction reference'),date('receivedOn','Received on')],['Receipts and allocations belong to the canonical finance workflow.','The portal remains inactive until advance settlement is verified.']),
  screen('Governance','acceptance','Acceptance & continuance','Prepare the appropriate client-risk checklist.',[choice('track','Review track',['New client acceptance','Recurring client continuance']),text('beneficialOwner','Ultimate beneficial owner'),memo('integrity','Management integrity and AML/KYC findings'),memo('independence','Independence and conflict checks'),memo('changes','Prior fees, ownership changes and litigation',false)],['Partner sign-off is required before operational planning.','Continuance requires a review of changes since the previous engagement.']),
  screen('Governance','schedule','Team & milestones','Prepare staff assignments and statutory milestones.',[text('partner','Engagement Partner'),text('manager','Audit Manager / Reviewer'),text('preparers','Assigned preparers'),date('fieldwork','Fieldwork start'),date('draftReport','Draft report due'),date('finalReport','Final report due'),memo('capacity','Capacity and leave constraints',false)],['Assignments are engagement scoped.','Capacity, leave and approval must be checked before confirming a schedule.']),
  screen('Governance','directories','Engagement directory','Prepare the SharePoint and OneDrive workspace structure.',[text('site','SharePoint workspace'),text('workingFolder','OneDrive working folder'),text('owner','Workspace owner')],['01 Administration & Planning · 02 Trial Balance & Schedules','03 Fieldwork & Testing · 04 Drafts & Deliverables · 05 Final Signed Archive']),
  screen('Governance','materiality','Materiality','Calculate planning thresholds from the current published balances.',[choice('benchmarkKind','Benchmark',['REVENUE','PROFIT_BEFORE_TAX','TOTAL_ASSETS','NET_ASSETS','TOTAL_EXPENSES','MAPPED_LINE']),text('destinationCode','Mapped line code (for mapped-line benchmark)',false),money('ratePercent','Benchmark rate · %'),money('performancePercent','Performance materiality · %'),money('trivialPercent','Trivial threshold · %')],['Amounts are calculated on the server from published balances.','Approval is separate from calculation and binds an exact assessment.'],'/materiality','Calculate assessment',['benchmarkKind','planningMateriality','performanceMateriality','trivialThreshold','approvedAt']),
  screen('Governance','risks','Risk register','Record risks and inspect their current assessed band.',[text('title','Risk title'),memo('description','Risk description',false)],['Risk bands and escalation are derived from the assessment on the server.','Red-risk clearance requires the assigned Partner authority.'],'/risks','Create risk',['title','currentBand','assessmentCount','cleared']),
  screen('Governance','lifecycle','Engagement lifecycle','Inspect the authoritative state and transition history.',[],['Only the server can advance an engagement after its gates are satisfied.','History is append-only; no state is inferred from navigation.'],'/lifecycle',undefined,['command','fromState','toState','createdAt'],'history'),
  screen('Fieldwork','trial-balance','Trial Balance','Import, map and finalize staged account balances.',[],['Each accounting period must balance before finalization.']),
  screen('Fieldwork','workprogram','Workprograms','Prepare assertion-based procedures and assigned testing.',[text('fsli','Financial statement line item'),choice('assertion','Assertion',['Ownership','Valuation','Completeness','Existence','Cut-off']),text('assignee','Assigned preparer'),memo('procedure','Audit procedure'),memo('result','Testing result',false)],['Custom procedures must remain traceable.','Submission and reviewer clearance are separate steps.']),
  screen('Fieldwork','evidence','Evidence register','Prepare digital references and physical binder indexes.',[text('workpackage','Workpackage reference'),text('document','Digital document reference',false),text('binder','Physical binder index',false),memo('description','Evidence description')],['Examples of physical references: X-1, Box 3.','Uploaded evidence versions remain immutable; SharePoint holds durable files.']),
  screen('Fieldwork','sampling','Sampling','Prepare a sampling request and document its population.',[choice('method','Sampling method',['Monetary Unit Sampling','Systematic Random','Stratified Attribute']),text('population','Population reference'),money('populationValue','Population value · QAR'),text('seed','Recorded random seed'),memo('objective','Testing objective')],['The server sampling engine supplies the selection.','A prepared request does not represent a selected or approved sample.']),
  screen('Fieldwork','analytics','Analytical review & going concern','Prepare comparative analysis and ISA 570 findings.',[text('fsli','Financial statement line item'),memo('movement','Movement explanation'),memo('goingConcern','Going-concern assessment'),memo('mitigation','Management plans and supporting evidence')],['Use published balance versions for comparative analysis.','Conclusions require documented review, not a dashboard calculation.']),
  screen('Fieldwork','adjustments','Audit adjustments','Prepare a two-line client adjustment, then post or reverse the exact journal version.',[text('reference','Journal reference'),memo('memo','Adjustment explanation'),text('accountCode1','First account code'),money('debit1','First debit � QAR'),money('credit1','First credit � QAR'),text('accountCode2','Second account code'),money('debit2','Second debit � QAR'),money('credit2','Second credit � QAR')],['Posted adjustments are immutable; corrections use reversal.','Firm expenses belong in Practice, never in client audit journals.'],'/adjustments','Create adjustment',['reference','memo','status','version']),
  screen('Fieldwork','confirmations','External confirmations','Prepare bank, receivable, legal and physical confirmations.',[choice('category','Confirmation category',['Bank','Receivable','Legal','Physical inventory']),text('recipient','Recipient'),text('reference','Request reference'),choice('critical','Release criticality',['Critical','Non-critical']),date('due','Response due'),memo('followup','Follow-up notes',false)],['Critical outstanding confirmations block report release.','No email or external request is sent by preparing this form.']),
  screen('Fieldwork','publications','Published balances','Publish a finalized import as an immutable accounting version.',[text('importId','Finalized import ID'),{...text('expectedVersion','Expected import version'),type:'integer'}],['Publication requires finalized balances and current mapping approval.'],'/publications/latest','Publish balances',['id','sequence','currency','rowCount','publishedAt']),
  screen('Reporting','reviews','Review notes','Raise anchored notes and inspect reviewer-owned resolution.',[text('workpackage','Workpackage reference'),memo('body','Review comment')],['The note author cannot resolve their own review note.','Resolution is a separate reviewer decision with an audit record.'],'/review-notes','Raise review note',['workpackage','body','status','raisedAt']),
  screen('Reporting','srm','Summary review memorandum','Prepare the matters requiring Partner attention.',[memo('significant','Significant audit matters'),memo('adjustments','Unadjusted differences'),memo('confirmations','Confirmation clearance'),memo('conclusion','Manager conclusion')],['The SRM follows manager clearance and zero blocking review notes.','Partner inspection focuses on significant and red-risk matters.']),
  screen('Reporting','opinion','Audit opinion','Prepare the Partner opinion and supporting basis.',[choice('opinion','Opinion',['Clean / Unqualified','Qualified','Disclaimer','Adverse']),text('fsli','Affected FSLI',false),memo('basis','Basis for modified opinion',false)],['Only the Engagement Partner can approve the opinion.','Modified opinions require the affected FSLI and a documented justification.']),
  screen('Reporting','management-letter','Management letter','Structure deficiencies, impacts and recommendations.',[text('area','Control area'),memo('deficiency','Deficiency'),memo('impact','Impact'),memo('recommendation','Auditor recommendation'),memo('response','Management response',false)],['The management letter is the second mandatory deliverable.']),
  screen('Reporting','representation','Representation letter','Prepare management representations and returned-signature evidence.',[text('executive','Authorized executive'),date('date','Representation date'),memo('representations','Management representations'),text('returnedDocument','Returned signed document reference',false)],['Obtain and verify signed management representations before report freeze.']),
  screen('Reporting','correspondence','Correspondence trail','Prepare formal enquiries and their closure references.',[text('subject','Subject'),text('recipient','Recipient'),date('sent','Correspondence date'),memo('response','Response and clearance evidence')],['The final package includes the management correspondence audit trail.','Preparation does not send an external message.']),
  screen('Reporting','signature','Partner signature & seal','Prepare artwork references and exact-version approval.',[text('partner','Approving Partner'),text('reportVersion','Report version reference'),text('signature','Signature artwork reference'),text('seal','Firm seal reference'),text('digest','Report SHA-256')],['Image signature and seal use the selected D08 assurance level.','Approval must bind the exact report bytes and immutable artwork versions.']),
  screen('Reporting','deliverables','Deliverable package','Prepare the five-part release checklist.',[text('report','D1 · Auditor report and financial statements'),text('letter','D2 · Management letter'),text('representation','D3 · Representation letter'),text('trail','D4 · Correspondence audit trail'),text('fee','D5 · Final balance fee note')],['All five parts are mandatory for the release package.','Release freezes client uploads and requires current approval lineage.']),
  screen('Reporting','archive','Compliance archive','Prepare assembly and read-only archive inspection.',[date('signatureDate','Partner signature date'),text('archive','Archive reference'),memo('assembly','Assembly checklist'),memo('hold','Legal hold / retention notes',false)],['The assembly window is 60 calendar days after signature.','Final locking is a server-controlled Partner action or scheduled transition.']),
  screen('Reporting','audit','Audit integrity','Verify the engagement audit chain through the protected API.',[],['Verification results come from the server.','An intact audit chain is separate from report signature assurance.'],'/audit/verify',undefined,['valid','reason']),
  screen('Practice','ledger','Firm ledger','Manage firm accounts, periods and balanced journals.',[],['Firm-wide accounting authority is required.']),
  screen('Practice','time','Time & utilization','Prepare daily time entries against engagement work.',[date('date','Work date'),text('staff','Staff member'),choice('phase','Engagement phase',['Planning','Fieldwork','Review','Reporting']),money('hours','Hours worked'),memo('activity','Work performed')],['Charge-out policies and realized profitability are calculated on the server.']),
  screen('Practice','profitability','Engagement profitability','Prepare budget and realization review.',[text('engagement','Engagement reference'),money('fee','Contracted audit fee · QAR'),money('budgetHours','Budget hours'),memo('variance','Variance commentary')],['Compare approved budgets with recorded staff time and approved rate snapshots.']),
  screen('Practice','receivables','Billing & receivables','Prepare allocations and collection follow-up.',[text('client','Client'),text('invoice','Invoice reference'),money('amount','Allocation amount · QAR'),date('due','Due date'),memo('followup','Collection follow-up',false)],['Advance and final invoices share the canonical ledger.','Receivable aging is based on actual allocated payments.']),
  screen('Practice','expenses','Operating expenses','Prepare expense and withdrawal supporting information.',[choice('category','Category',['Office rent','Staff salary','End of service & benefits','Partner withdrawal','Petty cash']),money('amount','Amount · QAR'),date('date','Accounting date'),text('reference','Supporting reference'),memo('memo','Description')],['Approved postings use the firm ledger and its accounting period.']),
  screen('Practice','statements','Firm financial reports','Prepare period selections for internal reporting.',[date('startsOn','Period start'),date('endsOn','Period end'),choice('report','Report',['Firm Trial Balance','Monthly Profit & Loss','Accounts Receivable Aging'])],['Statements must reconcile to firm postings and payment allocations.']),
];
export const modules: readonly ModuleName[] = ['Commercial','Governance','Fieldwork','Reporting','Practice'];
export const screensFor = (module: string) => moduleScreens.filter(screen => screen.module === module);
