export type ModuleName = 'Commercial' | 'Governance' | 'Fieldwork' | 'Reporting' | 'Practice';
export interface ScreenField { key: string; label: string; type?: 'text' | 'textarea' | 'date' | 'email' | 'decimal' | 'integer' | 'select'; required?: boolean; options?: readonly string[]; }
export interface ModuleScreen { id: string; module: ModuleName; title: string; description: string; fields: readonly ScreenField[]; columns: readonly { key: string; label: string }[]; endpoint?: string; collection?: string; action?: string; guidance: readonly string[]; lineKind?: 'adjustment' | 'taxonomy' | 'procedure' | 'evidence' | 'confirmation' | 'schedule'; }
const text = (key: string, label: string, required = true): ScreenField => ({ key, label, required });
const memo = (key: string, label: string, required = true): ScreenField => ({ key, label, type: 'textarea', required });
const date = (key: string, label: string): ScreenField => ({ key, label, type: 'date', required: true });
const money = (key: string, label: string): ScreenField => ({ key, label, type: 'decimal', required: true });
const choice = (key: string, label: string, options: readonly string[]): ScreenField => ({ key, label, type: 'select', required: true, options });
function screen(module: ModuleName, id: string, title: string, description: string, fields: ScreenField[], guidance: string[], endpoint?: string, action?: string, columnKeys?: string[], collection?: string): ModuleScreen {
  return { module, id, title, description, fields, guidance, endpoint, action, collection, columns: (columnKeys ?? fields.slice(0, 3).map(f => f.key)).map(key => ({ key, label: fields.find(f => f.key === key)?.label ?? key.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase()) })) };
}
export const moduleScreens: readonly ModuleScreen[] = [
  screen('Commercial','leads','Lead pipeline','Capture enquiries and prepare the next commercial conversation.',[text('legalName','Legal entity name'),choice('channel','Enquiry channel',['Phone','WhatsApp','Email','Website']),text('contactName','Primary contact'),{...text('email','Contact email'),type:'email'},memo('scope','Requested engagement scope')],['Capture the minimum entity and contact profile.','Client onboarding requires commercial acceptance and separate Partner risk clearance.']),
  screen('Commercial','entities','Entities & contacts','Organize corporate relationships and notification contacts.',[text('legalName','Legal entity name'),text('registration','Registration number'),text('parent','Holding company',false),choice('relationship','Entity relationship',['Independent','Holding','Subsidiary','Affiliate']),text('liaison','Audit liaison'),text('financeContact','Finance contact'),text('executiveContact','Executive contact')],['Financial notifications go to the designated finance contact.','Audit requests go to the audit liaison; representation requests go to management.']),
  {...screen('Commercial','proposals','Quotes & proposals','Create, present and record client acceptance of a versioned proposal.',[text('service','Service'),date('periodStart','Period start'),date('periodEnd','Period end'),money('totalAmount','Proposal fee · QAR')],['Presenting pins the exact revision snapshot.','Client acceptance records the Key 1 evidence reference.'],'/commercial/proposals','Create proposal',['service','status','revision','totalAmount'])},
  screen('Commercial','onboarding','Dual-key onboarding','Review client approval and independent risk clearance.',[text('entity','Client legal name'),text('proposalReference','Accepted proposal reference'),memo('clientApproval','Client acceptance evidence'),memo('partnerClearance','Partner AML/KYC clearance evidence')],['Both keys are required before generating an engagement letter.','A prepared checklist is not a recorded Partner approval.']),
  {...screen('Commercial','letters','Engagement letters','Inspect the ISA 210 letter issued by the dual-key lifecycle gate.',[],['The letter is issued by the ISSUE_ENGAGEMENT_LETTER lifecycle command, not by this screen.','Issued letters are immutable.'],'/commercial/dual-key',undefined,['letterIssued','letterText'])},
    {...screen('Commercial','advance','Advance billing & receipts','Issue the 50% advance invoice and record its settlement.',[date('dueOn','Invoice due date')],['The invoice amount is calculated from the exact accepted proposal.','The portal activates only after full payment and the official receipt.','Invoices are firm-numbered and owned by Practice.','An unpaid invoice can be voided with a reason; paid corrections require a credit-note workflow.'],'/practice/invoices','Issue advance invoice',['number','kind','status','amount','dueOn','paidToDate','receiptIssued'])},
  screen('Governance','acceptance','Acceptance & continuance','Prepare the appropriate client-risk checklist.',[choice('track','Review track',['New client acceptance','Recurring client continuance']),text('beneficialOwner','Ultimate beneficial owner'),memo('integrity','Management integrity and AML/KYC findings'),memo('independence','Independence and conflict checks'),memo('changes','Prior fees, ownership changes and litigation',false)],['Partner sign-off is required before operational planning.','Continuance requires a review of changes since the previous engagement.']),
  {...screen('Governance','schedule','Team & milestones','Prepare staff assignments and statutory milestones.',[text('partner','Engagement Partner'),text('manager','Audit Manager / Reviewer'),text('preparers','Assigned preparers'),date('fieldwork','Fieldwork start'),date('draftReport','Draft report due'),date('finalReport','Final report due'),memo('capacity','Capacity and leave constraints',false)],['Assignments are engagement scoped.','Capacity, leave and approval must be checked before confirming a schedule.']),lineKind:'schedule'},
  screen('Governance','directories','Engagement directory','Prepare the SharePoint and OneDrive workspace structure.',[text('site','SharePoint workspace'),text('workingFolder','OneDrive working folder'),text('owner','Workspace owner')],['01 Administration & Planning · 02 Trial Balance & Schedules','03 Fieldwork & Testing · 04 Drafts & Deliverables · 05 Final Signed Archive']),
  screen('Governance','materiality','Materiality','Calculate planning thresholds from the current published balances.',[choice('benchmarkKind','Benchmark',['REVENUE','PROFIT_BEFORE_TAX','TOTAL_ASSETS','NET_ASSETS','TOTAL_EXPENSES','MAPPED_LINE']),text('destinationCode','Mapped line code (for mapped-line benchmark)',false),money('ratePercent','Benchmark rate · %'),money('performancePercent','Performance materiality · %'),money('trivialPercent','Trivial threshold · %')],['Amounts are calculated on the server from published balances.','Approval is separate from calculation and binds an exact assessment.'],'/materiality','Calculate assessment',['benchmarkKind','planningMateriality','performanceMateriality','trivialThreshold','approvedAt']),
  screen('Governance','risks','Risk register','Record risks and inspect their current assessed band.',[text('title','Risk title'),memo('description','Risk description',false)],['Risk bands and escalation are derived from the assessment on the server.','Red-risk clearance requires the assigned Partner authority.'],'/risks','Create risk',['title','currentBand','assessmentCount','cleared']),
  screen('Governance','lifecycle','Engagement lifecycle','Inspect the authoritative state and transition history.',[],['Only the server can advance an engagement after its gates are satisfied.','History is append-only; no state is inferred from navigation.'],'/lifecycle',undefined,['command','fromState','toState','createdAt'],'history'),
  screen('Fieldwork','trial-balance','Trial Balance','Import, map and finalize staged account balances.',[],['Each accounting period must balance before finalization.']),
  {...screen('Fieldwork','workprogram','Workprograms','Prepare assertion-based procedures and assigned testing.',[text('fsli','Financial statement line item'),choice('assertion','Assertion',['Ownership','Valuation','Completeness','Existence','Cut-off']),text('assignee','Assigned preparer'),memo('procedure','Audit procedure'),memo('result','Testing result',false)],['Custom procedures must remain traceable.','Submission and reviewer clearance are separate steps.']),lineKind:'procedure'},
  {...screen('Fieldwork','evidence','Evidence register','Prepare digital references and physical binder indexes.',[text('workpackage','Workpackage reference'),text('document','Digital document reference',false),text('binder','Physical binder index',false),memo('description','Evidence description')],['Examples of physical references: X-1, Box 3.','Uploaded evidence versions remain immutable; SharePoint holds durable files.']),lineKind:'evidence'},
  screen('Fieldwork','sampling','Sampling','Prepare a sampling request and document its population.',[choice('method','Sampling method',['Monetary Unit Sampling','Systematic Random','Stratified Attribute']),text('population','Population reference'),money('populationValue','Population value · QAR'),text('seed','Recorded random seed'),memo('objective','Testing objective')],['The server sampling engine supplies the selection.','A prepared request does not represent a selected or approved sample.']),
  screen('Fieldwork','analytics','Analytical review & going concern','Prepare comparative analysis and ISA 570 findings.',[text('fsli','Financial statement line item'),memo('movement','Movement explanation'),memo('goingConcern','Going-concern assessment'),memo('mitigation','Management plans and supporting evidence')],['Use published balance versions for comparative analysis.','Conclusions require documented review, not a dashboard calculation.']),
  {...screen('Fieldwork','adjustments','Audit adjustments','Prepare a two-line client adjustment, then post or reverse the exact journal version.',[text('reference','Journal reference'),memo('memo','Adjustment explanation')],['Posted adjustments are immutable; corrections use reversal.','Firm expenses belong in Practice, never in client audit journals.'],'/adjustments','Create adjustment',['reference','memo','status','version']),lineKind:'adjustment'},
  {...screen('Fieldwork','confirmations','External confirmations','Prepare bank, receivable, legal and physical confirmations.',[choice('category','Confirmation category',['Bank','Receivable','Legal','Physical inventory']),text('recipient','Recipient'),text('reference','Request reference'),choice('critical','Release criticality',['Critical','Non-critical']),date('due','Response due'),memo('followup','Follow-up notes',false)],['Critical outstanding confirmations block report release.','No email or external request is sent by preparing this form.']),lineKind:'confirmation'},
  {...screen('Fieldwork','taxonomies','Taxonomy & mapping approval','Create versioned financial statement lines and approve an import mapping.',[text('name','Taxonomy name')],['Approved taxonomy versions are immutable.','Approve the mapping before finalizing and publishing an import.'],'/taxonomies','Create taxonomy',['name','version','status']),lineKind:'taxonomy'},
  screen('Fieldwork','publications','Published balances','Publish a finalized import as an immutable accounting version.',[text('importId','Finalized import ID'),{...text('expectedVersion','Expected import version'),type:'integer'}],['Publication requires finalized balances and current mapping approval.'],'/publications/latest','Publish balances',['id','sequence','currency','rowCount','publishedAt']),
  screen('Reporting','reviews','Review notes','Raise anchored notes and inspect reviewer-owned resolution.',[text('workpackage','Workpackage reference'),memo('body','Review comment')],['The note author cannot resolve their own review note.','Resolution is a separate reviewer decision with an audit record.'],'/review-notes','Raise review note',['workpackage','body','status','raisedAt']),
  screen('Reporting','templates','Document templates','Preview controlled document versions and manage approved firm artwork.',[],['Preview resolves only variables allowed by the selected immutable version.','Only users with the server-granted template management capability can create, approve or activate versions.','Image signature artwork is not a cryptographic signature.']),
  screen('Reporting','srm','Summary review memorandum','Prepare the matters requiring Partner attention.',[memo('significant','Significant audit matters'),memo('adjustments','Unadjusted differences'),memo('confirmations','Confirmation clearance'),memo('conclusion','Manager conclusion')],['The SRM follows manager clearance and zero blocking review notes.','Partner inspection focuses on significant and red-risk matters.']),
  screen('Reporting','opinion','Audit opinion','Prepare the Partner opinion and supporting basis.',[choice('opinion','Opinion',['Clean / Unqualified','Qualified','Disclaimer','Adverse']),text('fsli','Affected FSLI',false),memo('basis','Basis for modified opinion',false)],['Only the Engagement Partner can approve the opinion.','Modified opinions require the affected FSLI and a documented justification.']),
  screen('Reporting','management-letter','Management letter','Structure deficiencies, impacts and recommendations.',[text('area','Control area'),memo('deficiency','Deficiency'),memo('impact','Impact'),memo('recommendation','Auditor recommendation'),memo('response','Management response',false)],['The management letter is the second mandatory deliverable.']),
  screen('Reporting','representation','Representation letter','Prepare management representations and returned-signature evidence.',[text('executive','Authorized executive'),date('date','Representation date'),memo('representations','Management representations'),text('returnedDocument','Returned signed document reference',false)],['Obtain and verify signed management representations before report freeze.']),
  screen('Reporting','correspondence','Correspondence trail','Prepare formal enquiries and their closure references.',[text('subject','Subject'),text('recipient','Recipient'),date('sent','Correspondence date'),memo('response','Response and clearance evidence')],['The final package includes the management correspondence audit trail.','Preparation does not send an external message.']),
  screen('Reporting','signature','Partner signature & seal','Prepare artwork references and exact-version approval.',[text('partner','Approving Partner'),text('reportVersion','Report version reference'),text('signature','Signature artwork reference'),text('seal','Firm seal reference'),text('digest','Report SHA-256')],['Image signature and seal use the selected D08 assurance level.','Approval must bind the exact report bytes and immutable artwork versions.']),
  screen('Reporting','deliverables','Deliverable package','Prepare the five-part release checklist.',[text('report','D1 · Auditor report and financial statements'),text('letter','D2 · Management letter'),text('representation','D3 · Representation letter'),text('trail','D4 · Correspondence audit trail'),text('fee','D5 · Final balance fee note')],['All five parts are mandatory for the release package.','Release freezes client uploads and requires current approval lineage.']),
  screen('Reporting','archive','Compliance archive','Prepare assembly and read-only archive inspection.',[date('signatureDate','Partner signature date'),text('archive','Archive reference'),memo('assembly','Assembly checklist'),memo('hold','Legal hold / retention notes',false)],['The assembly window is 60 calendar days after signature.','Final locking is a server-controlled Partner action or scheduled transition.']),
  screen('Reporting','audit','Audit integrity','Verify the engagement audit chain through the protected API.',[],['Verification results come from the server.','An intact audit chain is separate from report signature assurance.'],'/audit/verify',undefined,['valid','reason']),
  screen('Practice','ledger','Firm ledger','Manage firm accounts, periods and balanced journals.',[],['Firm-wide accounting authority is required.']),
  screen('Practice','rates','Rate cards & staff grades','Set versioned charge-out rates and effective-dated professional grades.',[],['Job grade is separate from access role.','The captured charge-out value is not actual payroll cost.']),
  screen('Practice','time','Time & utilization','Prepare daily time entries against engagement work.',[date('date','Work date'),text('staff','Staff member'),choice('phase','Engagement phase',['Planning','Fieldwork','Review','Reporting']),money('hours','Hours worked'),memo('activity','Work performed')],['Charge-out policies and realized profitability are calculated on the server.']),
  screen('Practice','profitability','Engagement profitability','Prepare budget and realization review.',[text('engagement','Engagement reference'),money('fee','Contracted audit fee · QAR'),money('budgetHours','Budget hours'),memo('variance','Variance commentary')],['Compare approved budgets with recorded staff time and approved rate snapshots.']),
  screen('Practice','receivables','Billing & receivables','Prepare allocations and collection follow-up.',[text('client','Client'),text('invoice','Invoice reference'),money('amount','Allocation amount · QAR'),date('due','Due date'),memo('followup','Collection follow-up',false)],['Advance and final invoices share the canonical ledger.','Receivable aging is based on actual allocated payments.']),
  screen('Practice','expenses','Operating expenses','Record firm expense and withdrawal journals through approved chart and period controls.',[],['Expense receipt-version attachment remains in progress.']),
  screen('Practice','statements','Firm trial balance','Review period opening balances, posted journal movement, closing balances and account activity.',[],['Post-only report from the authoritative firm ledger.','Account drill-down preserves reversal lineage; CSV exports a deterministic report snapshot.']),
];
export const modules: readonly ModuleName[] = ['Commercial','Governance','Fieldwork','Reporting','Practice'];
export const screensFor = (module: string) => moduleScreens.filter(screen => screen.module === module);
