export { db, databasePool } from './platform/db.js';
export { CommercialController } from './modules/commercial/commercial-controller.js';
export { createProposal, presentProposal, acceptProposal, recordRiskClearance, dualKeyStatus, listProposals } from './modules/commercial/proposals.js';
export { createClient, updateClientProfile, setClientParent, listClientDirectory } from './modules/commercial/directory.js';
export { addContact, listContacts, resolveRecipient } from './modules/commercial/contacts.js';
export { createLead, listLeads, profileLead, advanceLeadToProposal } from './modules/commercial/leads.js';
export { createAcceptanceCase, recordAcceptanceAnswer, completeAcceptanceReview, clearAcceptanceCase } from './modules/commercial/acceptance.js';
export { createEngagement, engagementIdentity } from './modules/commercial/engagements.js';
export { generateProposalDocument, dispatchProposalDocument } from './modules/commercial/documents.js';
export { issueInvoice, recordInvoicePayment, issueInvoiceReceipt, voidInvoice, listInvoices } from './modules/practice/invoices.js';
export { PracticeLedgerController } from './modules/practice/ledger-controller.js';
export { approveFirmPostingPolicy, createPracticeAccount, createPracticePeriod, createPracticeJournal, createPracticeExpenseDraft, settlePracticeExpense, postPracticeJournal, reversePracticeJournal, closePracticePeriod, reopenPracticePeriod, practiceLedger } from './modules/practice/ledger.js';
export { PracticeRatesController } from './modules/practice/rates-controller.js';
export { ensurePracticeRateDefaultsForFirm, listPracticeRateAdministration, schedulePracticeRateCard, assignPracticeStaffGrade, recordAuthorizedPracticeTimeEntrySnapshot, calculatePracticeChargeOutValue } from './modules/practice/rates.js';
export type { PracticeTimeSnapshotInput } from './modules/practice/rates.js';
export { calculateContractContribution, validateContractContribution } from './modules/practice/analytics.js';
export type { ContractContribution, ContractTimeValue } from './modules/practice/analytics.js';
export { AuditController } from './platform/audit-controller.js';
export { captureAuditCheckpoint, verifyAuditChain, verifyAuditRecords, signAuditCheckpoint, verifySignedAuditCheckpoint } from './platform/audit-chain.js';
export type { AuditCheckpoint, AuditChainRow, SignedAuditCheckpoint } from './platform/audit-chain.js';
export { InternalGuard, InternalIdentityGuard, currentInternalIdentity, readableInternalEngagements, revokeCurrentUserSessions, authenticateEntraActor, authenticateRealtimeInternalActor, fixtureUser } from './platform/auth.js';
export { EntraIdentity } from './platform/entra.js';
export { InternalIdentityController } from './platform/identity-controller.js';
export { assignEngagementStaff, revokeEngagementStaff } from './platform/staff-access.js';
export { PortalAuthController } from './platform/portal-auth-controller.js';
export { DocumentUploadsController } from './platform/document-uploads-controller.js';
export { DocumentDownloadsController } from './platform/document-downloads-controller.js';
export { DocumentTemplatesController } from './platform/document-templates-controller.js';
export { listDocumentTemplateCatalog, createDocumentTemplate, appendDocumentTemplateVersion, decideDocumentTemplateVersion, changeDocumentTemplateActivation, previewDocumentTemplate, initiateApprovedAsset, initiateApprovedAssetVersion, receiveApprovedAsset, decideApprovedAsset, prepareApprovedAssetDownload, sweepUnfinishedDocumentTemplateAssetUploads } from './platform/document-templates.js';
export { compileDocumentTemplatePreview, documentTemplateDigest, templatePreviewHtml } from './platform/document-template-compiler.js';
export { prepareDocumentVersionDownload } from './platform/document-downloads.js';
export { PdfRenderError, renderAndPublishPdf, renderTrustedPdf } from './platform/pdf-renderer.js';
export { persistRenderedPdfVersion } from './platform/rendered-documents.js';
export type { PersistedRenderedPdfVersion, RenderedPdfAuthorizer } from './platform/rendered-documents.js';
export { initiateDocumentUpload, receiveDocumentUpload, finalizeDocumentUpload, getDocumentUploadSession } from './platform/document-uploads.js';
export { issuePortalInvitation, issuePortalPasswordReset, redeemPortalInvitation, loginPortalUser, completePortalPasswordReset, completePortalFirstLogin, resolvePortalSession, logoutPortalSession, assertPortalUploadAllowed, PORTAL_SESSION_COOKIE, PORTAL_SOCKET_SESSION_COOKIE, portalSessionTokenFromCookieHeader, portalSocketSessionTokenFromCookieHeader } from './platform/portal-auth.js';
export { requireCapability, hasCapability, anyCapability, grantCoversScope, revokeGrant } from './platform/authorization.js';
export { recordAuditEvent, recordSecurityEvent, redactValue, redactedMarker } from './platform/audit.js';
export type { AuditEventInput, SecurityEventInput } from './platform/audit.js';
export { FieldworkController } from './modules/fieldwork/controller.js';
export { GovernanceController } from './modules/governance/controller.js';
export { applyLifecycleCommand, lifecycleHistory, lifecycleGates, transitions, permittedCommands, canApply } from './modules/governance/lifecycle.js';
export { deriveBenchmark, validateMateriality, calculateMateriality, materialityInputHash, riskBand, minimumRiskOwnerRank, riskRoute, materialityBenchmarks, materialityPolicyVersion, riskBandRuleVersion } from './modules/governance/materiality.js';
export { MaterialityController } from './modules/governance/materiality-controller.js';
export { calculateMaterialityAssessment, approveMaterialityAssessment, latestMaterialityAssessment, listMaterialityAssessments } from './modules/governance/materiality-service.js';
export { RiskController } from './modules/governance/risk-controller.js';
export { createRisk, assessRiskBand, clearRiskBand, assignRiskOwner, currentRisks, riskStaffingRanks } from './modules/governance/risk-service.js';
export { ReviewNoteController } from './modules/reporting/review-notes-controller.js';
export { raiseReviewNote, resolveReviewNote, listReviewNotes, reviewSummary } from './modules/reporting/review-notes.js';
export { Decimal6, roundHalfEvenDiv, MONEY_SCALE, MAX_INTEGER_DIGITS } from './platform/decimal6.js';
export type { BalanceVariance, VarianceDirection } from './platform/decimal6.js';
export { SystemClock, FixedClock, AccountingDate, ClockModule, CLOCK, deadlineAfterCalendarDays } from './platform/clock.js';
export type { Clock } from './platform/clock.js';
export { UnitOfWork, runUnitOfWork, withUnitOfWork, lockForUpdate, isRetryableConflict, backoffDelay } from './platform/unit-of-work.js';
export type { TransactionClient, DatabaseClient, UnitOfWorkOptions, LockableTable } from './platform/unit-of-work.js';
export { normalizedRequestHash, startOperation, completeOperation, recordUnknownOperation } from './platform/idempotency.js';
export type { OperationScope, OperationKey, OperationStart } from './platform/idempotency.js';
export { calculateQuotation, validateQuotation, quotationInputHash, requiredApprovals, commercialRuleKinds, defaultDiscountThresholdPercent, defaultApprovalRole, quotationCurrencyScale, minimumComplexity, maximumComplexity, maximumPercent, maximumQuotationLines, maximumHoursPerLine } from './modules/commercial/quotation.js';
export type { QuotationPricingInput, QuotationPricingResult, QuotationLineInput, QuotationLineResult, CommercialApprovalRule, RequiredApproval } from './modules/commercial/quotation.js';
export type { MappedBenchmarkLine, MaterialityFigures, RiskBand, MaterialityBenchmark } from './modules/governance/materiality.js';
export type { Capability, Scope } from './platform/authorization.js';
export { parseTrialBalance, parseTrialBalanceStream, writeTrialBalanceChunks } from './modules/fieldwork/parser.js';
export { upload, mapBatch, finalize } from './modules/fieldwork/service.js';
export { AdjustmentController } from './modules/fieldwork/adjustments-controller.js';
export { createAdjustmentJournal, postAdjustmentJournal, reverseAdjustmentJournal, listAdjustmentJournals, adjustmentJournalDetail, adjustedBalances } from './modules/fieldwork/adjustments.js';
export { sweepUnreferencedUploads } from './modules/fieldwork/uploads.js';
export { PublicationController } from './modules/fieldwork/publication-controller.js';
export { DocumentLinksController } from './modules/fieldwork/document-links-controller.js';
export { listDocumentLinks, linkDocument, revokeDocumentLink } from './modules/fieldwork/document-links.js';
export { selectSample, drawIndexesFrom, samplingMethods } from './modules/fieldwork/sampling.js';
export { TaxonomyController } from './modules/fieldwork/taxonomy-controller.js';
export { createTaxonomyVersion, approveTaxonomyVersion, listTaxonomies, approveImportMapping, currentMappingApproval, suggestMappings, mappingDigest, taxonomySections } from './modules/fieldwork/taxonomy.js';
export type { SamplingPlan, SamplingOutcome, SampledItem, SamplingPopulationItem } from './modules/fieldwork/sampling.js';
export { publishBalances, latestPublication, publicationDetail, rowDigest } from './modules/fieldwork/publication.js';
export { runWorker } from './worker.js';
export { ensureBucket, store, retrieve, retrieveToFile, removeObject, storageProvider } from './platform/storage.js';
export { resolveClientRepository } from './platform/repository.js';
export { resolveFirmPracticeRepository } from './platform/repository.js';
export { attachPracticeExpenseReceipt, listPracticeExpenseReceipts, sweepPracticeExpenseReceiptUploads } from './modules/practice/expense-receipts.js';
export { GraphStorage, configuredGraphStorage, decodeGraphReference } from './platform/graph-storage.js';
export { RuntimeModule, Readiness, OPERATIONAL_METRICS, REDIS_HEALTH_PROBE, createRedisHealthProbe } from './platform/runtime.js';
export type { ReadinessResult, RedisHealthProbe } from './platform/runtime.js';
export { CorrelationContextInterceptor, currentCorrelationId, createCorrelationId, runWithCorrelationId, validCorrelationId } from './platform/observability/correlation.js';
export { OperationalMetrics, operationalMetrics } from './platform/observability/metrics.js';
export type { QueueName, ProviderName, DependencyState, QueueSnapshot, PoolSnapshot } from './platform/observability/metrics.js';
export { metricsAuthorized, createMetricsServer, listenMetricsServer } from './platform/observability/metrics-http.js';
export { safeLogFields, safeOperationalCode } from './platform/observability/logging.js';
export { NotificationController } from './platform/notifications-controller.js';
export { createRoutedNotification, snapshotAuthorizedRecipients, GraphMailProvider, configuredGraphMailProvider, dispatchPendingNotifications, listNotificationInbox, listOutboundMessages, markNotificationRead, retryFailedOutbound, reconcileUnknownOutbound } from './platform/notifications.js';
export type { AuthorizedContact, ContactRole, NotificationEvent, RecipientSnapshot } from './platform/notifications.js';
export { readConfiguration } from './platform/config.js';
export { RealtimeModule } from './platform/realtime/module.js';
export { EditLeaseConnection } from './platform/leases.js';
export { scheduleDeadline, cancelScheduledDeadline, enqueueDueDeadlines, createScheduledDeadlineProcessor } from './platform/scheduler.js';
export type { DeadlineClassification, ScheduleDeadlineInput, ScheduledDeadlineContext, ScheduledDeadlineHandler, ScheduledDeadlineHandlers } from './platform/scheduler.js';
export { RealtimeGateway } from './platform/realtime/gateway.js';
export { authorizeRealtimeJoin, resolveRealtimePrincipal } from './platform/realtime/authorization.js';
export type { RealtimePrincipal, AuthorizedRealtimeJoin } from './platform/realtime/authorization.js';
export { publishRealtimeInvalidation, subscribeRealtimeInvalidations } from './platform/realtime/invalidation.js';
export { internalEngagementRoom, internalImportRoom, portalEngagementRoom } from './platform/realtime/rooms.js';
export { installRealtimeRedisAdapter } from './platform/realtime/redis-transport.js';
